apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: thimee/udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 128Mi
            cpu: 200m
        envFrom:
          - secretRef:
              name: postgres-credentials
          - configMapRef:
              name: secret-config
          - secretRef:
              name: aws-credentials
