apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: thimee/udagram-api-feed
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2000Mi"
            cpu: "500m"
          requests:
            memory: "1000Mi"
            cpu: "200m"
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: secret-config
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: aws-credentials
      volumes:
        - name: aws-credentials
          configMap:
            name: aws-credentials
